In [1]:
#Importing required libraries
import pandas as pd 
import numpy as np

In [2]:
#reading the data
data=pd.read_csv('data_cleaned.csv')

In [3]:
#first five rows of the data
data.head()

,Survived,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Sex_female,Sex_male,SibSp_0,SibSp_1,...,Parch_0,Parch_1,Parch_2,Parch_3,Parch_4,Parch_5,Parch_6,Embarked_C,Embarked_Q,Embarked_S
0,0,22.0,7.2500,0,0,1,0,1,0,1,...,1,0,0,0,0,0,0,0,0,1
1,1,38.0,71.2833,1,0,0,1,0,0,1,...,1,0,0,0,0,0,0,1,0,0
2,1,26.0,7.9250,0,0,1,1,0,1,0,...,1,0,0,0,0,0,0,0,0,1
3,1,35.0,53.1000,1,0,0,1,0,0,1,...,1,0,0,0,0,0,0,0,0,1
4,0,35.0,8.0500,0,0,1,0,1,1,0,...,1,0,0,0,0,0,0,0,0,1

In [5]:
#independent variables
x = data.drop(['Survived'], axis=1)

#dependent variable
y = data['Survived']

In [6]:
#import the train-test split
from sklearn.model_selection import train_test_split
#divide into train and test sets
train_x,test_x,train_y,test_y = train_test_split(x,y, random_state = 101, stratify=y)

In [7]:
#Importing XGBM Classifier 
from xgboost import XGBClassifier

In [ ]:
#creating an extreme Gradient boosting instance
clf = XGBClassifier(random_state=96)
#training the model
clf.fit(train_x,train_y)
#calculating score on training data
clf.score(train_x, train_y).
#calculating score on test data
clf.score(test_x, test_y)

# Hyperparamter Tuning

Same as GBDT

1. **n_estimators:** Total number of trees
2. **learning_rate:**This determines the impact of each tree on the final outcome
3. **random_state:** The random number seed so that same random numbers are generated every time
4. **max_depth:** Maximum depth to which tree can grow (stopping criteria)
5. **subsample:** The fraction of observations to be selected for each tree. Selection is done by random sampling
6. **objective:** Defines Loss function (*binary:logistic* is for classification using probability, *reg:logistic* is for classification, *reg:linear* is for regression)
7. **colsample_bylevel:** Random feature selection at levels
8. **colsample_bytree:** Random feature selection at tree

In [ ]:
#set parameters
clf = XGBClassifier(random_state=96, colsample_bytree=0.7, max_depth=6)
#training the model
clf.fit(train_x,train_y)
#calculating score on test data
clf.score(test_x, test_y)

# Regularization

1. **gamma:** Minimum reduction in loss at every split
2. **reg_alpha:** Makes leaf weights 0
3. **reg_lambda:** Decrease leaf weights more smoothly